development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: simplecodereview_development
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: simplecodereview_test
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      database: <%= ENV['MONGOID_DATABASE'] %>
  options:
    identity_map_enabled: true
